### PR TITLE
CSIC-73 Added treeq resize unit test cases for controller

### PR DESCRIPTION
**Pull request by dhanashreebiradar**
Added treeq resize unit test cases for controller

### CODE REVIEW

**Review by gadekarnitesh — APPROVED** [review]
lg

**Review by nikhilbarge — APPROVED** [review]
lg

**Review by gadekarnitesh — APPROVED** [review]
lg

**Comment by gadekarnitesh** [comment]
different PR raised against 
https://github.com/Infinidat/infinibox-csi-driver/pull/56

**Pull request closed without merging**
